name: Flyway Migrate

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flyway
        uses: suzuki-shunsuke/github-action-flyway@v2
        with:
          flyway-version: '11.13.0'
      - name: Run Flyway migrations
        env:
          FLYWAY_URL: jdbc:postgresql://db.ssedpniisaibygkwrsbm.supabase.co:5432/postgres?sslmode=require
          FLYWAY_USER: postgres.ssedpniisaibygkwrsbm
          FLYWAY_PASSWORD: ${{ secrets.DB_PASS }}
        run: flyway -locations=filesystem:flyway/sql -configFiles=flyway/conf/flyway.conf migrate
