name: Flyway Migrate

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flyway CLI (official download)
        run: |
          curl -sSL https://download.red-gate.com/maven/release/org/flywaydb/flyway-commandline/11.13.0/flyway-commandline-11.13.0-linux-x64.tar.gz -o flyway.tar.gz
          tar -xzf flyway.tar.gz
          sudo ln -s "$(pwd)/flyway-11.13.0/flyway" /usr/local/bin/flyway
          flyway -v

      - name: Run Flyway migrations
        env:
          FLYWAY_URL: jdbc:postgresql://db.ssedpniisaibygkwrsbm.supabase.co:5432/postgres?sslmode=require
          FLYWAY_USER: postgres.ssedpniisaibygkwrsbm
          FLYWAY_PASSWORD: ${{ secrets.DB_PASS }}
        run: |
          flyway \
            -url=$FLYWAY_URL \
            -user=$FLYWAY_USER \
            -password=$FLYWAY_PASSWORD \
            -locations=filesystem:flyway/sql \
            -configFiles=flyway/conf/flyway.conf \
            migrate
